import { CRAWLER_GROUPS, STATUS, OUTCOME, analyzeRobots, analyzeLlms } from './parser.js';

const STATUS_LABEL = {
  [STATUS.ALLOWED]: 'Allowed',
  [STATUS.BLOCKED]: 'Blocked',
  [STATUS.PARTIAL]: 'Partly blocked',
  [STATUS.UNKNOWN]: 'Unknown',
};

const UNREACHABLE_TEXT = {
  'http-401': 'returned HTTP 401. That is often bot protection, so statuses are Unknown rather than Allowed.',
  'http-403': 'returned HTTP 403. That is often bot protection, so statuses are Unknown rather than Allowed.',
  'http-429': 'returned HTTP 429 (rate limited), so statuses are Unknown.',
  'http-5xx': 'returned a server error, so statuses are Unknown.',
  'http-other': 'returned a response that could not be interpreted, so statuses are Unknown.',
  network: 'could not be fetched (network error, bot protection, or a cross-origin redirect), so statuses are Unknown.',
};

const $ = (id) => document.getElementById(id);

function show(el, visible = true) {
  el.hidden = !visible;
}

// One fetch with a single silent retry. The activeTab grant's CORS
// allowlist update is asynchronous, so the very first request after the
// popup opens can race it; one short retry absorbs that.
async function fetchFile(url) {
  const attempt = async () => {
    const res = await fetch(url, { redirect: 'follow', credentials: 'omit', cache: 'no-store' });
    return {
      status: res.status,
      contentType: res.headers.get('content-type') || '',
      body: await res.text(),
    };
  };
  try {
    return await attempt();
  } catch {
    await new Promise((r) => setTimeout(r, 150));
    try {
      return await attempt();
    } catch {
      return { networkError: true };
    }
  }
}

function renderResults(robots) {
  const tbody = $('results-body');
  tbody.replaceChildren();
  for (const { group, bots } of CRAWLER_GROUPS) {
    const groupRow = document.createElement('tr');
    groupRow.className = 'group-row';
    const th = document.createElement('th');
    th.colSpan = 2;
    th.textContent = group;
    groupRow.append(th);
    tbody.append(groupRow);

    for (const bot of bots) {
      const row = document.createElement('tr');
      row.className = 'bot-row';
      const nameCell = document.createElement('td');
      nameCell.textContent = bot;
      const statusCell = document.createElement('td');
      statusCell.className = 'status-cell';
      const pill = document.createElement('span');
      const status = robots.bots[bot];
      pill.className = 'pill ' + status;
      pill.textContent = STATUS_LABEL[status];
      statusCell.append(pill);
      row.append(nameCell, statusCell);
      tbody.append(row);
    }
  }
  show($('results'));
}

function renderNotes(robots, llms) {
  const notes = [];
  if (robots.outcome === OUTCOME.UNREACHABLE) {
    notes.push('robots.txt ' + UNREACHABLE_TEXT[robots.reason]);
  }
  if (llms.state === 'unknown') {
    notes.push('llms.txt ' + UNREACHABLE_TEXT[llms.reason]);
  }
  if (notes.length > 0) {
    const noteEl = $('note');
    noteEl.replaceChildren();
    for (const text of notes) {
      const p = document.createElement('p');
      p.textContent = text;
      noteEl.append(p);
    }
    show(noteEl);
  }
}

function renderLlms(llms) {
  const statusEl = $('llms-status');
  if (llms.state === 'present') {
    statusEl.textContent = 'Present';
    const bodyEl = $('llms-body');
    bodyEl.textContent = llms.body;
    show(bodyEl);
  } else if (llms.state === 'not_found') {
    statusEl.textContent = 'Not found';
  } else {
    statusEl.textContent = 'Unknown';
  }
  show($('llms-section'));
}

function buildReport(domain, robots, llms) {
  const lines = ['AI Crawler Check: ' + domain, ''];
  if (robots.outcome === OUTCOME.PARSED) {
    lines.push('robots.txt: found and parsed');
  } else if (robots.outcome === OUTCOME.MISSING) {
    lines.push('robots.txt: not found, all crawlers allowed');
  } else {
    lines.push('robots.txt: unreachable, statuses unknown');
  }
  lines.push('');
  for (const { group, bots } of CRAWLER_GROUPS) {
    lines.push(group);
    for (const bot of bots) {
      lines.push('  ' + bot + ': ' + STATUS_LABEL[robots.bots[bot]]);
    }
  }
  lines.push('');
  const llmsLabel = { present: 'Present', not_found: 'Not found', unknown: 'Unknown' };
  lines.push('llms.txt: ' + llmsLabel[llms.state]);
  lines.push('');
  lines.push('Generated by AI Crawler Check, built by GOJI');
  lines.push('https://goji.agency/tools/ai-crawler-check');
  return lines.join('\n');
}

function setupCopyButton(domain, robots, llms) {
  const button = $('copy-button');
  button.addEventListener('click', async () => {
    try {
      await navigator.clipboard.writeText(buildReport(domain, robots, llms));
      button.textContent = 'Copied';
    } catch {
      button.textContent = 'Copy failed';
    }
    setTimeout(() => {
      button.textContent = 'Copy report';
    }, 1500);
  });
  show(button);
}

function showCannotCheck() {
  const message = $('message');
  message.textContent = 'Cannot check this page';
  show(message);
}

async function init() {
  let origin = null;
  let hostname = null;
  try {
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    if (tab && tab.url) {
      const url = new URL(tab.url);
      if (url.protocol === 'http:' || url.protocol === 'https:') {
        origin = url.origin;
        hostname = url.hostname;
      }
    }
  } catch {
    // Fall through to the unsupported-page state.
  }

  if (!origin) {
    showCannotCheck();
    return;
  }

  const domainEl = $('domain');
  domainEl.textContent = hostname;
  show(domainEl);

  const message = $('message');
  message.textContent = 'Checking ' + hostname + '...';
  show(message);

  const [robotsResponse, llmsResponse] = await Promise.all([
    fetchFile(origin + '/robots.txt'),
    fetchFile(origin + '/llms.txt'),
  ]);

  const robots = analyzeRobots(robotsResponse);
  const llms = analyzeLlms(llmsResponse);

  show(message, false);
  renderNotes(robots, llms);
  renderResults(robots);
  renderLlms(llms);
  setupCopyButton(hostname, robots, llms);
}

init();
